name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ['**']
    tags:
      - '**'
jobs:
  build_and_test_ros2:
    runs-on: ubuntu-24.04 # Use the noble Ubuntu LTS version
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Clone eeg_msgs package 
        run: |
          git clone https://github.com/sense-base/sense_msgs.git

      - name: ⚙️ Install libraries
        run: |
          sudo apt-get update
          sudo apt-get -y install libusb-dev

      - name: Build gtec_eeg_publisher ROS 2
        uses: ros-tooling/action-ros-ci@0.4.3
        # add an environment variable containing a personal access token for
        # download access to gtec drivers. GTEC_TOKEN secret may need adding or updating.
        # https://github.com/sense-base/sense_acquisition_gtech/settings/secrets/actions
        env: 
          GTEC_TOKEN: ${{ secrets.GTEC_TOKEN }}
        with:
          package-name: eeg_msgs gtec_eeg_publisher
          target-ros2-distro: jazzy # I tried humble but didn't seem to work with ament 
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
              "mixin": ["coverage-gcc"]
              }
              "packages-up-to": [
                "eeg_msgs"
              ]
            }
