name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'
jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@0.4.3
        # add an environment variable containing a personal access token for
        # download access to gtec drivers. GTEC_TOKEN secret may need adding or updating.
        # https://github.com/sense-base/sense_acquisition_gtech/settings/secrets/actions
        env: 
          GTEC_TOKEN: ${{ secrets.GTEC_TOKEN }}
        with:
          package-name: sense_eeg
          target-ros2-distro: jazzy
